title: Koba
description: Koba, bridge between Knockout and Backbone
url: http://mathieumast.github.io/koba/
github: http://github.com/mathieumast/koba

links:
  - title: Exemples
    url: exemples/
  - title: License
    url: license/

markdown: kramdown
permalink: pretty

exclude: ["nbproject"]
